// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hub_transactions.sql

package db

import (
	"context"
)

const insertHubTransaction = `-- name: InsertHubTransaction :exec
INSERT INTO hub_transactions (
    ref_id,
    player_id,
    type,
    amount_cents,
    currency,
    operator_status,
    operator_balance
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertHubTransactionParams struct {
	RefID           string
	PlayerID        string
	Type            string
	AmountCents     int64
	Currency        string
	OperatorStatus  string
	OperatorBalance int64
}

func (q *Queries) InsertHubTransaction(ctx context.Context, arg InsertHubTransactionParams) error {
	_, err := q.db.Exec(ctx, insertHubTransaction,
		arg.RefID,
		arg.PlayerID,
		arg.Type,
		arg.AmountCents,
		arg.Currency,
		arg.OperatorStatus,
		arg.OperatorBalance,
	)
	return err
}

const listHubTransactions = `-- name: ListHubTransactions :many
SELECT id, ref_id, player_id, type, amount_cents, currency, operator_status, operator_balance, created_at
FROM hub_transactions
ORDER BY id DESC
`

func (q *Queries) ListHubTransactions(ctx context.Context) ([]HubTransaction, error) {
	rows, err := q.db.Query(ctx, listHubTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HubTransaction
	for rows.Next() {
		var i HubTransaction
		if err := rows.Scan(
			&i.ID,
			&i.RefID,
			&i.PlayerID,
			&i.Type,
			&i.AmountCents,
			&i.Currency,
			&i.OperatorStatus,
			&i.OperatorBalance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
