// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package db

import (
	"context"
)

const getIdempotency = `-- name: GetIdempotency :one
SELECT response
FROM idempotency_keys
WHERE key = $1
`

func (q *Queries) GetIdempotency(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getIdempotency, key)
	var response []byte
	err := row.Scan(&response)
	return response, err
}

const saveIdempotency = `-- name: SaveIdempotency :exec
INSERT INTO idempotency_keys (key, response)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET response = EXCLUDED.response
`

type SaveIdempotencyParams struct {
	Key      string
	Response []byte
}

func (q *Queries) SaveIdempotency(ctx context.Context, arg SaveIdempotencyParams) error {
	_, err := q.db.Exec(ctx, saveIdempotency, arg.Key, arg.Response)
	return err
}
