// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyKey struct {
	ID        int32
	Key       string
	Response  []byte
	CreatedAt pgtype.Timestamptz
}
