// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HubTransaction struct {
	ID              int64
	RefID           string
	PlayerID        string
	Type            string
	AmountCents     int64
	Currency        string
	OperatorStatus  string
	OperatorBalance int64
	CreatedAt       pgtype.Timestamptz
}

type IdempotencyKey struct {
	ID        int32
	Key       string
	Response  []byte
	CreatedAt pgtype.Timestamptz
}

type WebhookOutbox struct {
	ID            int64
	EventID       string
	Payload       []byte
	Status        string
	AttemptCount  int32
	NextAttemptAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}
