// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetIdempotency(ctx context.Context, key string) ([]byte, error)
	SaveIdempotency(ctx context.Context, arg SaveIdempotencyParams) error
}

var _ Querier = (*Queries)(nil)
