// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetDueWebhooks(ctx context.Context) ([]GetDueWebhooksRow, error)
	GetIdempotency(ctx context.Context, key string) ([]byte, error)
	GetWebhookByEventID(ctx context.Context, eventID string) (WebhookOutbox, error)
	IncrementWebhookAttempt(ctx context.Context, id int64) error
	InsertWebhookOutbox(ctx context.Context, arg InsertWebhookOutboxParams) error
	MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) error
	MarkWebhookSuccess(ctx context.Context, id int64) error
	SaveIdempotency(ctx context.Context, arg SaveIdempotencyParams) error
}

var _ Querier = (*Queries)(nil)
