// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook_outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDueWebhooks = `-- name: GetDueWebhooks :many
SELECT id, event_id, payload, status, attempt_count, next_attempt_at
FROM webhook_outbox
WHERE status = 'PENDING'
  AND next_attempt_at <= NOW()
ORDER BY id
    LIMIT 50
`

type GetDueWebhooksRow struct {
	ID            int64
	EventID       string
	Payload       []byte
	Status        string
	AttemptCount  int32
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) GetDueWebhooks(ctx context.Context) ([]GetDueWebhooksRow, error) {
	rows, err := q.db.Query(ctx, getDueWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueWebhooksRow
	for rows.Next() {
		var i GetDueWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookFailed = `-- name: MarkWebhookFailed :exec
UPDATE webhook_outbox
SET status = 'FAILED',
    attempt_count = attempt_count + 1,
    next_attempt_at = $2
WHERE id = $1
`

type MarkWebhookFailedParams struct {
	ID            int64
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) MarkWebhookFailed(ctx context.Context, arg MarkWebhookFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookFailed, arg.ID, arg.NextAttemptAt)
	return err
}

const markWebhookSuccess = `-- name: MarkWebhookSuccess :exec
UPDATE webhook_outbox
SET status = 'SUCCESS', attempt_count = attempt_count + 1
WHERE id = $1
`

func (q *Queries) MarkWebhookSuccess(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markWebhookSuccess, id)
	return err
}
