// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hub_webhooks.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const hubWebhookEventExists = `-- name: HubWebhookEventExists :one
SELECT EXISTS (
    SELECT 1
    FROM hub_webhook_events
    WHERE event_id = $1
)
`

func (q *Queries) HubWebhookEventExists(ctx context.Context, eventID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hubWebhookEventExists, eventID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertHubWebhookEvent = `-- name: InsertHubWebhookEvent :exec
INSERT INTO hub_webhook_events (event_id, payload)
VALUES ($1, $2)
    ON CONFLICT (event_id) DO NOTHING
`

type InsertHubWebhookEventParams struct {
	EventID string          `json:"event_id"`
	Payload json.RawMessage `json:"payload"`
}

func (q *Queries) InsertHubWebhookEvent(ctx context.Context, arg InsertHubWebhookEventParams) error {
	_, err := q.db.ExecContext(ctx, insertHubWebhookEvent, arg.EventID, arg.Payload)
	return err
}
